#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

#puts "TODO: setup this script to call your WACC compiler"

if ARGV.empty?
  puts "No file provided, please provide a .WACC file to compile"
elsif File.extname(ARGV[0]) != ".wacc"
  puts "Not a .wacc file, please provide a .WACC file to compile"
else
  #{}%x(java out/waccTest.class < #{ARGV[0]})
  x = "java -cp bin:lib/antlr-4.7-complete.jar src/waccTest < #{ARGV[0]}"
  exec x
end
