#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.


if ARGV.empty?
  puts "No file provided, please provide a .WACC file to compile"
elsif File.extname(ARGV[0]) != ".wacc"
  puts "Not a .wacc file, please provide a .WACC file to compile"
else
  x = "java -cp bin:lib/antlr-4.7-complete.jar src/waccMain #{ARGV[0]} < #{ARGV[0]}"
  exec x
end
